apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: 2048-app

  template:
    metadata:
      labels:
        app: 2048-app

    spec:
      containers:
        - name: 2048-app
          image: 156204501476.dkr.ecr.eu-west-2.amazonaws.com/2048-app:v2
          ports:
            - containerPort: 80