provider:
  name: cloudflare

sources:
  - ingress

domainFilters:
  - nabilenv.com

policy: upsert-only

registry: txt
txtOwnerId: 2048-eks-platform

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: apiToken